name: TestSachin JMeter Action

on:
  workflow_dispatch:

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v5.6.2
        with:
          testFilePath: tests/sample_test.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO"

      - name: Run JMeter Action on other tests
        uses: rbhadti94/apache-jmeter-action@v5.6.2
        with:
          testFilePath: other-tests/
          outputReportsFolder: other_reports/
          args: "--loglevel INFO"

      - uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results
          path: reports/

      - uses: actions/upload-artifact@v3
        with:
          name: jmeter-test-results-other
          path: other_reports/
          if-no-files-found: error
